name: poco
channels:
  - defaults
  - conda-forge
  - anaconda
  - pytorch
  - nvidia
dependencies:
  - python==3.10.14
  - pytorch==2.4.0
  - pytorch-cuda==12.1
  - torchaudio
  - torchvision
  - scikit-learn
  - scipy
  - tqdm
  - anaconda::h5py
  - pandas
  - matplotlib
  - conda-forge::torchmetrics
  - conda-forge::pytorch-lightning
  - conda-forge::einops
  - pip
  - conda-forge::umap-learn
  - pip:
    - mat73
    - tensorstore
    - xformers
    - torchtyping