name: metafish
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=23.3.1
  - python=3.11.0
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==1.2.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - appdirs==1.4.4
      - arrow==1.3.0
      - asciitree==0.3.3
      - attrs==23.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bidsschematools==0.7.2
      - blessed==1.20.0
      - bokeh==3.0.3
      - boto3==1.34.69
      - botocore==1.34.69
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - ci-info==0.3.0
      - click==8.1.7
      - click-didyoumean==0.3.0
      - cmake==3.28.4
      - configargparse==1.7
      - connection-pool==0.0.3
      - contourpy==1.2.0
      - croniter==1.4.1
      - cryptography==42.0.5
      - cycler==0.12.1
      - dandi==0.56.1
      - dandischema==0.8.4
      - dateutils==0.6.12
      - datrie==0.8.2
      - decorator==5.1.1
      - deepdiff==6.7.1
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docutils==0.20.1
      - dpath==2.1.6
      - editor==1.6.6
      - einops==0.6.1
      - email-validator==2.1.1
      - etelemetry==0.3.1
      - fastapi==0.110.0
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - fonttools==4.50.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fscacher==0.4.0
      - fsspec==2024.3.1
      - gitdb==4.0.11
      - gitpython==3.1.42
      - grpcio==1.62.1
      - h11==0.14.0
      - h5py==3.8.0
      - hdmf==3.13.0
      - humanfriendly==10.0
      - humanize==4.9.0
      - hydra-core==1.3.2
      - idna==3.6
      - imageio==2.34.0
      - importlib-metadata==7.1.0
      - iniconfig==2.0.0
      - inquirer==3.2.4
      - interleave==0.2.1
      - isodate==0.6.1
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jaraco-classes==3.3.1
      - jaraco-context==4.3.0
      - jaraco-functools==4.0.0
      - jeepney==0.8.0
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - keopscore==2.2.2
      - keyring==25.0.0
      - keyrings-alt==5.0.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning==2.0.8
      - lightning-cloud==0.5.65
      - lightning-utilities==0.11.0
      - lit==18.1.2
      - markdown==3.6
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mdurl==0.1.2
      - mne==1.6.1
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - natsort==8.4.0
      - nbformat==5.10.3
      - networkx==3.2.1
      - numcodecs==0.12.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - nwbinspector==0.4.33
      - omegaconf==2.3.0
      - ordered-set==4.1.0
      - packaging==24.0
      - pandas==1.3.5
      - pillow==10.2.0
      - plac==1.4.3
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - pooch==1.8.1
      - protobuf==4.25.3
      - psutil==5.9.8
      - pulp==2.7.0
      - pybind11==2.12.0
      - pycparser==2.21
      - pycryptodomex==3.20.0
      - pydantic==1.10.13
      - pygments==2.17.2
      - pyjwt==2.8.0
      - pympler==1.0.1
      - pynwb==2.2.0
      - pyout==0.7.3
      - pyparsing==3.1.2
      - pytest==7.2.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - pytorch-lightning==2.2.1
      - pytorch-ranger==0.1.1
      - pytz==2024.1
      - pywavelets==1.5.0
      - pyyaml==6.0.1
      - readchar==4.0.6
      - referencing==0.34.0
      - requests==2.31.0
      - reretry==0.11.8
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rich==13.3.2
      - rpds-py==0.18.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - runs==1.2.2
      - s3fs==0.4.2
      - s3transfer==0.10.1
      - scikit-image==0.19.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - sentry-sdk==1.43.0
      - setproctitle==1.3.3
      - setuptools==60.2.0
      - six==1.16.0
      - smart-open==7.0.3
      - smmap==5.0.1
      - snakemake==7.32.4
      - sniffio==1.3.1
      - soupsieve==2.5
      - starlette==0.36.3
      - starsessions==1.3.0
      - stopit==1.1.2
      - sympy==1.11.1
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorly==0.8.1
      - threadpoolctl==3.4.0
      - throttler==1.2.2
      - tifffile==2024.2.12
      - toposort==1.10
      - torch==2.0.1
      - torch-optimizer==0.3.0
      - torchdata==0.6.1
      - torchmetrics==1.3.2
      - torchtext==0.15.2
      - torchtyping==0.1.4
      - tornado==6.4
      - tqdm==4.64.1
      - traitlets==5.14.2
      - triton==2.0.0
      - typeguard==4.1.5
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.10.0
      - uri-template==1.3.0
      - urllib3==2.2.1
      - uvicorn==0.29.0
      - wandb==0.16.4
      - wcwidth==0.2.13
      - webcolors==1.13
      - websocket-client==1.7.0
      - websockets==12.0
      - werkzeug==3.0.1
      - wget==3.2
      - wrapt==1.16.0
      - xformers==0.0.21
      - xmod==1.8.1
      - xyzservices==2023.10.1
      - yarl==1.9.4
      - yte==1.5.4
      - zarr==2.17.1
      - zarr-checksum==0.4.0
      - zenodo-get==1.5.1
      - zipp==3.18.1
