name: metafish
channels:
  - defaults
dependencies:
  - python==3.10.14
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - xformers
  - scikit-learn
  - scipy
  - tqdm
  - anaconda::h5py
  - pandas
  - matplotlib
  - conda-forge::einops
  - conda-forge::torchmetrics
  - conda-forge::pytorch-lightning
  - pip:
    - mat73
    - tensorstore
    - git+https://github.com/google-research/zapbench.git#egg=zapbench